package org.brewchain.cwv.dbgens.game.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.cwv.dbgens.game.entity.CWVGameTxHandle;
import org.brewchain.cwv.dbgens.game.entity.CWVGameTxHandleExample;
import org.brewchain.cwv.dbgens.game.entity.CWVGameTxHandleKey;

public interface CWVGameTxHandleMapper extends StaticTableDaoSupport<CWVGameTxHandle, CWVGameTxHandleExample, CWVGameTxHandleKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @SelectProvider(type=CWVGameTxHandleSqlProvider.class, method="countByExample")
    int countByExample(CWVGameTxHandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @DeleteProvider(type=CWVGameTxHandleSqlProvider.class, method="deleteByExample")
    int deleteByExample(CWVGameTxHandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Delete({
        "delete from cwv_game_tx_handle",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(CWVGameTxHandleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Insert({
        "insert into cwv_game_tx_handle (id, type, ",
        "tx_hash, description, ",
        "status)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{txHash,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(CWVGameTxHandle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @InsertProvider(type=CWVGameTxHandleSqlProvider.class, method="insertSelective")
    int insertSelective(CWVGameTxHandle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @SelectProvider(type=CWVGameTxHandleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="tx_hash", property="txHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<CWVGameTxHandle> selectByExample(CWVGameTxHandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Select({
        "select",
        "id, type, tx_hash, description, status",
        "from cwv_game_tx_handle",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="tx_hash", property="txHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    CWVGameTxHandle selectByPrimaryKey(CWVGameTxHandleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @UpdateProvider(type=CWVGameTxHandleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CWVGameTxHandle record, @Param("example") CWVGameTxHandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @UpdateProvider(type=CWVGameTxHandleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CWVGameTxHandle record, @Param("example") CWVGameTxHandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @UpdateProvider(type=CWVGameTxHandleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CWVGameTxHandle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Update({
        "update cwv_game_tx_handle",
        "set type = #{type,jdbcType=INTEGER},",
          "tx_hash = #{txHash,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CWVGameTxHandle record);
}