package org.brewchain.cwv.dbgens.game.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.cwv.dbgens.game.entity.CWVGameMap;
import org.brewchain.cwv.dbgens.game.entity.CWVGameMapExample.Criteria;
import org.brewchain.cwv.dbgens.game.entity.CWVGameMapExample.Criterion;
import org.brewchain.cwv.dbgens.game.entity.CWVGameMapExample;

public class CWVGameMapSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String countByExample(CWVGameMapExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cwv_game_map");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String deleteByExample(CWVGameMapExample example) {
        BEGIN();
        DELETE_FROM("cwv_game_map");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String insertSelective(CWVGameMap record) {
        BEGIN();
        INSERT_INTO("cwv_game_map");
        
        if (record.getMapId() != null) {
            VALUES("map_id", "#{mapId,jdbcType=INTEGER}");
        }
        
        if (record.getMapName() != null) {
            VALUES("map_name", "#{mapName,jdbcType=VARCHAR}");
        }
        
        if (record.getMapNameZh() != null) {
            VALUES("map_name_zh", "#{mapNameZh,jdbcType=VARCHAR}");
        }
        
        if (record.getGameCityId() != null) {
            VALUES("game_city_id", "#{gameCityId,jdbcType=INTEGER}");
        }
        
        if (record.getTemplate() != null) {
            VALUES("template", "#{template,jdbcType=INTEGER}");
        }
        
        if (record.getImageUrl() != null) {
            VALUES("image_url", "#{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            VALUES("created_time", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalCount() != null) {
            VALUES("total_count", "#{totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisplay() != null) {
            VALUES("is_display", "#{isDisplay,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String selectByExample(CWVGameMapExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("map_id");
        } else {
            SELECT("map_id");
        }
        SELECT("map_name");
        SELECT("map_name_zh");
        SELECT("game_city_id");
        SELECT("template");
        SELECT("image_url");
        SELECT("created_time");
        SELECT("status");
        SELECT("total_count");
        SELECT("is_display");
        FROM("cwv_game_map");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("cwv_game_map");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >=0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CWVGameMap record = (CWVGameMap) parameter.get("record");
        CWVGameMapExample example = (CWVGameMapExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cwv_game_map");
        
        if (record.getMapId() != null) {
            SET("map_id = #{record.mapId,jdbcType=INTEGER}");
        }
        
        if (record.getMapName() != null) {
            SET("map_name = #{record.mapName,jdbcType=VARCHAR}");
        }
        
        if (record.getMapNameZh() != null) {
            SET("map_name_zh = #{record.mapNameZh,jdbcType=VARCHAR}");
        }
        
        if (record.getGameCityId() != null) {
            SET("game_city_id = #{record.gameCityId,jdbcType=INTEGER}");
        }
        
        if (record.getTemplate() != null) {
            SET("template = #{record.template,jdbcType=INTEGER}");
        }
        
        if (record.getImageUrl() != null) {
            SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{record.status,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalCount() != null) {
            SET("total_count = #{record.totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisplay() != null) {
            SET("is_display = #{record.isDisplay,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cwv_game_map");
        
        SET("map_id = #{record.mapId,jdbcType=INTEGER}");
        SET("map_name = #{record.mapName,jdbcType=VARCHAR}");
        SET("map_name_zh = #{record.mapNameZh,jdbcType=VARCHAR}");
        SET("game_city_id = #{record.gameCityId,jdbcType=INTEGER}");
        SET("template = #{record.template,jdbcType=INTEGER}");
        SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
        SET("status = #{record.status,jdbcType=VARCHAR}");
        SET("total_count = #{record.totalCount,jdbcType=INTEGER}");
        SET("is_display = #{record.isDisplay,jdbcType=VARCHAR}");
        
        CWVGameMapExample example = (CWVGameMapExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    public String updateByPrimaryKeySelective(CWVGameMap record) {
        BEGIN();
        UPDATE("cwv_game_map");
        
        if (record.getMapName() != null) {
            SET("map_name = #{mapName,jdbcType=VARCHAR}");
        }
        
        if (record.getMapNameZh() != null) {
            SET("map_name_zh = #{mapNameZh,jdbcType=VARCHAR}");
        }
        
        if (record.getGameCityId() != null) {
            SET("game_city_id = #{gameCityId,jdbcType=INTEGER}");
        }
        
        if (record.getTemplate() != null) {
            SET("template = #{template,jdbcType=INTEGER}");
        }
        
        if (record.getImageUrl() != null) {
            SET("image_url = #{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("created_time = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalCount() != null) {
            SET("total_count = #{totalCount,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisplay() != null) {
            SET("is_display = #{isDisplay,jdbcType=VARCHAR}");
        }
        
        WHERE("map_id = #{mapId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_map
     *
     * @mbggenerated Sat Jul 07 13:30:28 CST 2018
     */
    protected void applyWhere(CWVGameMapExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}