package org.brewchain.cwv.dbgens.game.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.cwv.dbgens.game.entity.CWVGameDic;
import org.brewchain.cwv.dbgens.game.entity.CWVGameDicExample.Criteria;
import org.brewchain.cwv.dbgens.game.entity.CWVGameDicExample.Criterion;
import org.brewchain.cwv.dbgens.game.entity.CWVGameDicExample;

public class CWVGameDicSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String countByExample(CWVGameDicExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cwv_game_dic");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String deleteByExample(CWVGameDicExample example) {
        BEGIN();
        DELETE_FROM("cwv_game_dic");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String insertSelective(CWVGameDic record) {
        BEGIN();
        INSERT_INTO("cwv_game_dic");
        
        if (record.getDicId() != null) {
            VALUES("dic_id", "#{dicId,jdbcType=INTEGER}");
        }
        
        if (record.getDicKey() != null) {
            VALUES("dic_key", "#{dicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValue() != null) {
            VALUES("dic_value", "#{dicValue,jdbcType=VARCHAR}");
        }
        
        if (record.getParentKey() != null) {
            VALUES("parent_key", "#{parentKey,jdbcType=VARCHAR}");
        }
        
        if (record.getParentValue() != null) {
            VALUES("parent_value", "#{parentValue,jdbcType=VARCHAR}");
        }
        
        if (record.getSeq() != null) {
            VALUES("seq", "#{seq,jdbcType=SMALLINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String selectByExample(CWVGameDicExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("dic_id");
        } else {
            SELECT("dic_id");
        }
        SELECT("dic_key");
        SELECT("dic_value");
        SELECT("parent_key");
        SELECT("parent_value");
        SELECT("seq");
        FROM("cwv_game_dic");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("cwv_game_dic");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >=0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CWVGameDic record = (CWVGameDic) parameter.get("record");
        CWVGameDicExample example = (CWVGameDicExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cwv_game_dic");
        
        if (record.getDicId() != null) {
            SET("dic_id = #{record.dicId,jdbcType=INTEGER}");
        }
        
        if (record.getDicKey() != null) {
            SET("dic_key = #{record.dicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValue() != null) {
            SET("dic_value = #{record.dicValue,jdbcType=VARCHAR}");
        }
        
        if (record.getParentKey() != null) {
            SET("parent_key = #{record.parentKey,jdbcType=VARCHAR}");
        }
        
        if (record.getParentValue() != null) {
            SET("parent_value = #{record.parentValue,jdbcType=VARCHAR}");
        }
        
        if (record.getSeq() != null) {
            SET("seq = #{record.seq,jdbcType=SMALLINT}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cwv_game_dic");
        
        SET("dic_id = #{record.dicId,jdbcType=INTEGER}");
        SET("dic_key = #{record.dicKey,jdbcType=VARCHAR}");
        SET("dic_value = #{record.dicValue,jdbcType=VARCHAR}");
        SET("parent_key = #{record.parentKey,jdbcType=VARCHAR}");
        SET("parent_value = #{record.parentValue,jdbcType=VARCHAR}");
        SET("seq = #{record.seq,jdbcType=SMALLINT}");
        
        CWVGameDicExample example = (CWVGameDicExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    public String updateByPrimaryKeySelective(CWVGameDic record) {
        BEGIN();
        UPDATE("cwv_game_dic");
        
        if (record.getDicKey() != null) {
            SET("dic_key = #{dicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getDicValue() != null) {
            SET("dic_value = #{dicValue,jdbcType=VARCHAR}");
        }
        
        if (record.getParentKey() != null) {
            SET("parent_key = #{parentKey,jdbcType=VARCHAR}");
        }
        
        if (record.getParentValue() != null) {
            SET("parent_value = #{parentValue,jdbcType=VARCHAR}");
        }
        
        if (record.getSeq() != null) {
            SET("seq = #{seq,jdbcType=SMALLINT}");
        }
        
        WHERE("dic_id = #{dicId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Mon Jun 11 21:03:55 CST 2018
     */
    protected void applyWhere(CWVGameDicExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}