package org.brewchain.cwv.dbgens.game.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.cwv.dbgens.game.entity.CWVGameProperty;
import org.brewchain.cwv.dbgens.game.entity.CWVGamePropertyExample.Criteria;
import org.brewchain.cwv.dbgens.game.entity.CWVGamePropertyExample.Criterion;
import org.brewchain.cwv.dbgens.game.entity.CWVGamePropertyExample;

public class CWVGamePropertySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String countByExample(CWVGamePropertyExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cwv_game_property");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String deleteByExample(CWVGamePropertyExample example) {
        BEGIN();
        DELETE_FROM("cwv_game_property");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String insertSelective(CWVGameProperty record) {
        BEGIN();
        INSERT_INTO("cwv_game_property");
        
        if (record.getPropertyId() != null) {
            VALUES("property_id", "#{propertyId,jdbcType=INTEGER}");
        }
        
        if (record.getGameMapId() != null) {
            VALUES("game_map_id", "#{gameMapId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getPropertyName() != null) {
            VALUES("property_name", "#{propertyName,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyType() != null) {
            VALUES("property_type", "#{propertyType,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertySubType() != null) {
            VALUES("property_sub_type", "#{propertySubType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyMarketType() != null) {
            VALUES("property_market_type", "#{propertyMarketType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyStatus() != null) {
            VALUES("property_status", "#{propertyStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getLastPrice() != null) {
            VALUES("last_price", "#{lastPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceIncrease() != null) {
            VALUES("price_increase", "#{priceIncrease,jdbcType=DECIMAL}");
        }
        
        if (record.getLastPriceTime() != null) {
            VALUES("last_price_time", "#{lastPriceTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageUrl() != null) {
            VALUES("image_url", "#{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getIncome() != null) {
            VALUES("income", "#{income,jdbcType=DECIMAL}");
        }
        
        if (record.getIsDisplay() != null) {
            VALUES("is_display", "#{isDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            VALUES("created_time", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPropertyTemplateId() != null) {
            VALUES("property_template_id", "#{propertyTemplateId,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyTemplate() != null) {
            VALUES("property_template", "#{propertyTemplate,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            VALUES("longitude", "#{longitude,jdbcType=VARCHAR}");
        }
        
        if (record.getLatitude() != null) {
            VALUES("latitude", "#{latitude,jdbcType=VARCHAR}");
        }
        
        if (record.getCryptoToken() != null) {
            VALUES("crypto_token", "#{cryptoToken,jdbcType=VARCHAR}");
        }
        
        if (record.getChainStatus() != null) {
            VALUES("chain_status", "#{chainStatus,jdbcType=TINYINT}");
        }
        
        if (record.getChainTransHash() != null) {
            VALUES("chain_trans_hash", "#{chainTransHash,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String selectByExample(CWVGamePropertyExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("property_id");
        } else {
            SELECT("property_id");
        }
        SELECT("game_map_id");
        SELECT("user_id");
        SELECT("property_name");
        SELECT("property_type");
        SELECT("property_sub_type");
        SELECT("property_market_type");
        SELECT("property_status");
        SELECT("last_price");
        SELECT("price_increase");
        SELECT("last_price_time");
        SELECT("image_url");
        SELECT("income");
        SELECT("is_display");
        SELECT("created_time");
        SELECT("property_template_id");
        SELECT("property_template");
        SELECT("longitude");
        SELECT("latitude");
        SELECT("crypto_token");
        SELECT("chain_status");
        SELECT("chain_trans_hash");
        FROM("cwv_game_property");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("cwv_game_property");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >=0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CWVGameProperty record = (CWVGameProperty) parameter.get("record");
        CWVGamePropertyExample example = (CWVGamePropertyExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cwv_game_property");
        
        if (record.getPropertyId() != null) {
            SET("property_id = #{record.propertyId,jdbcType=INTEGER}");
        }
        
        if (record.getGameMapId() != null) {
            SET("game_map_id = #{record.gameMapId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getPropertyName() != null) {
            SET("property_name = #{record.propertyName,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyType() != null) {
            SET("property_type = #{record.propertyType,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertySubType() != null) {
            SET("property_sub_type = #{record.propertySubType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyMarketType() != null) {
            SET("property_market_type = #{record.propertyMarketType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyStatus() != null) {
            SET("property_status = #{record.propertyStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getLastPrice() != null) {
            SET("last_price = #{record.lastPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceIncrease() != null) {
            SET("price_increase = #{record.priceIncrease,jdbcType=DECIMAL}");
        }
        
        if (record.getLastPriceTime() != null) {
            SET("last_price_time = #{record.lastPriceTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageUrl() != null) {
            SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getIncome() != null) {
            SET("income = #{record.income,jdbcType=DECIMAL}");
        }
        
        if (record.getIsDisplay() != null) {
            SET("is_display = #{record.isDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPropertyTemplateId() != null) {
            SET("property_template_id = #{record.propertyTemplateId,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyTemplate() != null) {
            SET("property_template = #{record.propertyTemplate,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            SET("longitude = #{record.longitude,jdbcType=VARCHAR}");
        }
        
        if (record.getLatitude() != null) {
            SET("latitude = #{record.latitude,jdbcType=VARCHAR}");
        }
        
        if (record.getCryptoToken() != null) {
            SET("crypto_token = #{record.cryptoToken,jdbcType=VARCHAR}");
        }
        
        if (record.getChainStatus() != null) {
            SET("chain_status = #{record.chainStatus,jdbcType=TINYINT}");
        }
        
        if (record.getChainTransHash() != null) {
            SET("chain_trans_hash = #{record.chainTransHash,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cwv_game_property");
        
        SET("property_id = #{record.propertyId,jdbcType=INTEGER}");
        SET("game_map_id = #{record.gameMapId,jdbcType=INTEGER}");
        SET("user_id = #{record.userId,jdbcType=INTEGER}");
        SET("property_name = #{record.propertyName,jdbcType=VARCHAR}");
        SET("property_type = #{record.propertyType,jdbcType=VARCHAR}");
        SET("property_sub_type = #{record.propertySubType,jdbcType=TINYINT}");
        SET("property_market_type = #{record.propertyMarketType,jdbcType=TINYINT}");
        SET("property_status = #{record.propertyStatus,jdbcType=VARCHAR}");
        SET("last_price = #{record.lastPrice,jdbcType=DECIMAL}");
        SET("price_increase = #{record.priceIncrease,jdbcType=DECIMAL}");
        SET("last_price_time = #{record.lastPriceTime,jdbcType=TIMESTAMP}");
        SET("image_url = #{record.imageUrl,jdbcType=VARCHAR}");
        SET("income = #{record.income,jdbcType=DECIMAL}");
        SET("is_display = #{record.isDisplay,jdbcType=VARCHAR}");
        SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
        SET("property_template_id = #{record.propertyTemplateId,jdbcType=VARCHAR}");
        SET("property_template = #{record.propertyTemplate,jdbcType=VARCHAR}");
        SET("longitude = #{record.longitude,jdbcType=VARCHAR}");
        SET("latitude = #{record.latitude,jdbcType=VARCHAR}");
        SET("crypto_token = #{record.cryptoToken,jdbcType=VARCHAR}");
        SET("chain_status = #{record.chainStatus,jdbcType=TINYINT}");
        SET("chain_trans_hash = #{record.chainTransHash,jdbcType=VARCHAR}");
        
        CWVGamePropertyExample example = (CWVGamePropertyExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String updateByPrimaryKeySelective(CWVGameProperty record) {
        BEGIN();
        UPDATE("cwv_game_property");
        
        if (record.getGameMapId() != null) {
            SET("game_map_id = #{gameMapId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getPropertyName() != null) {
            SET("property_name = #{propertyName,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyType() != null) {
            SET("property_type = #{propertyType,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertySubType() != null) {
            SET("property_sub_type = #{propertySubType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyMarketType() != null) {
            SET("property_market_type = #{propertyMarketType,jdbcType=TINYINT}");
        }
        
        if (record.getPropertyStatus() != null) {
            SET("property_status = #{propertyStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getLastPrice() != null) {
            SET("last_price = #{lastPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPriceIncrease() != null) {
            SET("price_increase = #{priceIncrease,jdbcType=DECIMAL}");
        }
        
        if (record.getLastPriceTime() != null) {
            SET("last_price_time = #{lastPriceTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getImageUrl() != null) {
            SET("image_url = #{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getIncome() != null) {
            SET("income = #{income,jdbcType=DECIMAL}");
        }
        
        if (record.getIsDisplay() != null) {
            SET("is_display = #{isDisplay,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("created_time = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPropertyTemplateId() != null) {
            SET("property_template_id = #{propertyTemplateId,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyTemplate() != null) {
            SET("property_template = #{propertyTemplate,jdbcType=VARCHAR}");
        }
        
        if (record.getLongitude() != null) {
            SET("longitude = #{longitude,jdbcType=VARCHAR}");
        }
        
        if (record.getLatitude() != null) {
            SET("latitude = #{latitude,jdbcType=VARCHAR}");
        }
        
        if (record.getCryptoToken() != null) {
            SET("crypto_token = #{cryptoToken,jdbcType=VARCHAR}");
        }
        
        if (record.getChainStatus() != null) {
            SET("chain_status = #{chainStatus,jdbcType=TINYINT}");
        }
        
        if (record.getChainTransHash() != null) {
            SET("chain_trans_hash = #{chainTransHash,jdbcType=VARCHAR}");
        }
        
        WHERE("property_id = #{propertyId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_property
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    protected void applyWhere(CWVGamePropertyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}