package org.brewchain.cwv.dbgens.market.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketExchangeBuy;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketExchangeBuyExample;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketExchangeBuyKey;

public interface CWVMarketExchangeBuyMapper extends StaticTableDaoSupport<CWVMarketExchangeBuy, CWVMarketExchangeBuyExample, CWVMarketExchangeBuyKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @SelectProvider(type=CWVMarketExchangeBuySqlProvider.class, method="countByExample")
    int countByExample(CWVMarketExchangeBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @DeleteProvider(type=CWVMarketExchangeBuySqlProvider.class, method="deleteByExample")
    int deleteByExample(CWVMarketExchangeBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @Delete({
        "delete from cwv_market_exchange_buy",
        "where exchange_id = #{exchangeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(CWVMarketExchangeBuyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @Insert({
        "insert into cwv_market_exchange_buy (exchange_id, amount, ",
        "buyer_address, seller_address, ",
        "status, chain_status, ",
        "chain_trans_hash, property_token, ",
        "chain_status_group, chain_trans_hash_group, ",
        "chain_status_rollback, chain_trans_hash_rollback)",
        "values (#{exchangeId,jdbcType=INTEGER}, #{amount,jdbcType=DECIMAL}, ",
        "#{buyerAddress,jdbcType=VARCHAR}, #{sellerAddress,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{chainStatus,jdbcType=TINYINT}, ",
        "#{chainTransHash,jdbcType=VARCHAR}, #{propertyToken,jdbcType=VARCHAR}, ",
        "#{chainStatusGroup,jdbcType=TINYINT}, #{chainTransHashGroup,jdbcType=VARCHAR}, ",
        "#{chainStatusRollback,jdbcType=TINYINT}, #{chainTransHashRollback,jdbcType=VARCHAR})"
    })
    int insert(CWVMarketExchangeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @InsertProvider(type=CWVMarketExchangeBuySqlProvider.class, method="insertSelective")
    int insertSelective(CWVMarketExchangeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @SelectProvider(type=CWVMarketExchangeBuySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="exchange_id", property="exchangeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_address", property="buyerAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="seller_address", property="sellerAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="chain_status", property="chainStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash", property="chainTransHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="property_token", property="propertyToken", jdbcType=JdbcType.VARCHAR),
        @Result(column="chain_status_group", property="chainStatusGroup", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash_group", property="chainTransHashGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="chain_status_rollback", property="chainStatusRollback", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash_rollback", property="chainTransHashRollback", jdbcType=JdbcType.VARCHAR)
    })
    List<CWVMarketExchangeBuy> selectByExample(CWVMarketExchangeBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @Select({
        "select",
        "exchange_id, amount, buyer_address, seller_address, status, chain_status, chain_trans_hash, ",
        "property_token, chain_status_group, chain_trans_hash_group, chain_status_rollback, ",
        "chain_trans_hash_rollback",
        "from cwv_market_exchange_buy",
        "where exchange_id = #{exchangeId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="exchange_id", property="exchangeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DECIMAL),
        @Result(column="buyer_address", property="buyerAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="seller_address", property="sellerAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="chain_status", property="chainStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash", property="chainTransHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="property_token", property="propertyToken", jdbcType=JdbcType.VARCHAR),
        @Result(column="chain_status_group", property="chainStatusGroup", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash_group", property="chainTransHashGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="chain_status_rollback", property="chainStatusRollback", jdbcType=JdbcType.TINYINT),
        @Result(column="chain_trans_hash_rollback", property="chainTransHashRollback", jdbcType=JdbcType.VARCHAR)
    })
    CWVMarketExchangeBuy selectByPrimaryKey(CWVMarketExchangeBuyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @UpdateProvider(type=CWVMarketExchangeBuySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CWVMarketExchangeBuy record, @Param("example") CWVMarketExchangeBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @UpdateProvider(type=CWVMarketExchangeBuySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CWVMarketExchangeBuy record, @Param("example") CWVMarketExchangeBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @UpdateProvider(type=CWVMarketExchangeBuySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CWVMarketExchangeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exchange_buy
     *
     * @mbggenerated Sat Jul 14 19:27:12 CST 2018
     */
    @Update({
        "update cwv_market_exchange_buy",
        "set amount = #{amount,jdbcType=DECIMAL},",
          "buyer_address = #{buyerAddress,jdbcType=VARCHAR},",
          "seller_address = #{sellerAddress,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "chain_status = #{chainStatus,jdbcType=TINYINT},",
          "chain_trans_hash = #{chainTransHash,jdbcType=VARCHAR},",
          "property_token = #{propertyToken,jdbcType=VARCHAR},",
          "chain_status_group = #{chainStatusGroup,jdbcType=TINYINT},",
          "chain_trans_hash_group = #{chainTransHashGroup,jdbcType=VARCHAR},",
          "chain_status_rollback = #{chainStatusRollback,jdbcType=TINYINT},",
          "chain_trans_hash_rollback = #{chainTransHashRollback,jdbcType=VARCHAR}",
        "where exchange_id = #{exchangeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CWVMarketExchangeBuy record);
}