package org.brewchain.cwv.dbgens.market.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketAuctionList;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketAuctionListExample;
import org.brewchain.cwv.dbgens.market.entity.CWVMarketAuctionListKey;

public interface CWVMarketAuctionListMapper extends StaticTableDaoSupport<CWVMarketAuctionList, CWVMarketAuctionListExample, CWVMarketAuctionListKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @SelectProvider(type=CWVMarketAuctionListSqlProvider.class, method="countByExample")
    int countByExample(CWVMarketAuctionListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @DeleteProvider(type=CWVMarketAuctionListSqlProvider.class, method="deleteByExample")
    int deleteByExample(CWVMarketAuctionListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @Delete({
        "delete from cwv_market_auction_list",
        "where auction_id = #{auctionId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(CWVMarketAuctionListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @Insert({
        "insert into cwv_market_auction_list (auction_id, bid_id, ",
        "nick_name, bid_price, ",
        "user_id, create_time, ",
        "create_user)",
        "values (#{auctionId,jdbcType=INTEGER}, #{bidId,jdbcType=INTEGER}, ",
        "#{nickName,jdbcType=TIMESTAMP}, #{bidPrice,jdbcType=TIMESTAMP}, ",
        "#{userId,jdbcType=DECIMAL}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createUser,jdbcType=VARCHAR})"
    })
    int insert(CWVMarketAuctionList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @InsertProvider(type=CWVMarketAuctionListSqlProvider.class, method="insertSelective")
    int insertSelective(CWVMarketAuctionList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @SelectProvider(type=CWVMarketAuctionListSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="auction_id", property="auctionId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="bid_id", property="bidId", jdbcType=JdbcType.INTEGER),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bid_price", property="bidPrice", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR)
    })
    List<CWVMarketAuctionList> selectByExample(CWVMarketAuctionListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @Select({
        "select",
        "auction_id, bid_id, nick_name, bid_price, user_id, create_time, create_user",
        "from cwv_market_auction_list",
        "where auction_id = #{auctionId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="auction_id", property="auctionId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="bid_id", property="bidId", jdbcType=JdbcType.INTEGER),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bid_price", property="bidPrice", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR)
    })
    CWVMarketAuctionList selectByPrimaryKey(CWVMarketAuctionListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @UpdateProvider(type=CWVMarketAuctionListSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CWVMarketAuctionList record, @Param("example") CWVMarketAuctionListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @UpdateProvider(type=CWVMarketAuctionListSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CWVMarketAuctionList record, @Param("example") CWVMarketAuctionListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @UpdateProvider(type=CWVMarketAuctionListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CWVMarketAuctionList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction_list
     *
     * @mbggenerated Tue Apr 10 11:08:41 CST 2018
     */
    @Update({
        "update cwv_market_auction_list",
        "set bid_id = #{bidId,jdbcType=INTEGER},",
          "nick_name = #{nickName,jdbcType=TIMESTAMP},",
          "bid_price = #{bidPrice,jdbcType=TIMESTAMP},",
          "user_id = #{userId,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR}",
        "where auction_id = #{auctionId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CWVMarketAuctionList record);
}