package org.brewchain.cwv.dbgens.user.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.brewchain.cwv.dbgens.user.entity.CWVUserWallet;
import org.brewchain.cwv.dbgens.user.entity.CWVUserWalletExample.Criteria;
import org.brewchain.cwv.dbgens.user.entity.CWVUserWalletExample.Criterion;
import org.brewchain.cwv.dbgens.user.entity.CWVUserWalletExample;

public class CWVUserWalletSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String countByExample(CWVUserWalletExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cwv_user_wallet");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String deleteByExample(CWVUserWalletExample example) {
        BEGIN();
        DELETE_FROM("cwv_user_wallet");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String insertSelective(CWVUserWallet record) {
        BEGIN();
        INSERT_INTO("cwv_user_wallet");
        
        if (record.getWalletId() != null) {
            VALUES("wallet_id", "#{walletId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getCoinType() != null) {
            VALUES("coin_type", "#{coinType,jdbcType=TINYINT}");
        }
        
        if (record.getAccount() != null) {
            VALUES("account", "#{account,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            VALUES("balance", "#{balance,jdbcType=DECIMAL}");
        }
        
        if (record.getTopupBalance() != null) {
            VALUES("topup_balance", "#{topupBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getDrawCount() != null) {
            VALUES("draw_count", "#{drawCount,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountHistory() != null) {
            VALUES("draw_count_history", "#{drawCountHistory,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountRecord() != null) {
            VALUES("draw_count_record", "#{drawCountRecord,jdbcType=INTEGER}");
        }
        
        if (record.getIncomeOrdinary() != null) {
            VALUES("income_ordinary", "#{incomeOrdinary,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeTypical() != null) {
            VALUES("income_typical", "#{incomeTypical,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeFunctional() != null) {
            VALUES("income_functional", "#{incomeFunctional,jdbcType=DECIMAL}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCoinIcon() != null) {
            VALUES("coin_icon", "#{coinIcon,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String selectByExample(CWVUserWalletExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("wallet_id");
        } else {
            SELECT("wallet_id");
        }
        SELECT("user_id");
        SELECT("coin_type");
        SELECT("account");
        SELECT("balance");
        SELECT("topup_balance");
        SELECT("draw_count");
        SELECT("draw_count_history");
        SELECT("draw_count_record");
        SELECT("income_ordinary");
        SELECT("income_typical");
        SELECT("income_functional");
        SELECT("update_time");
        SELECT("create_time");
        SELECT("coin_icon");
        FROM("cwv_user_wallet");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("cwv_user_wallet");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >=0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CWVUserWallet record = (CWVUserWallet) parameter.get("record");
        CWVUserWalletExample example = (CWVUserWalletExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cwv_user_wallet");
        
        if (record.getWalletId() != null) {
            SET("wallet_id = #{record.walletId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getCoinType() != null) {
            SET("coin_type = #{record.coinType,jdbcType=TINYINT}");
        }
        
        if (record.getAccount() != null) {
            SET("account = #{record.account,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            SET("balance = #{record.balance,jdbcType=DECIMAL}");
        }
        
        if (record.getTopupBalance() != null) {
            SET("topup_balance = #{record.topupBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getDrawCount() != null) {
            SET("draw_count = #{record.drawCount,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountHistory() != null) {
            SET("draw_count_history = #{record.drawCountHistory,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountRecord() != null) {
            SET("draw_count_record = #{record.drawCountRecord,jdbcType=INTEGER}");
        }
        
        if (record.getIncomeOrdinary() != null) {
            SET("income_ordinary = #{record.incomeOrdinary,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeTypical() != null) {
            SET("income_typical = #{record.incomeTypical,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeFunctional() != null) {
            SET("income_functional = #{record.incomeFunctional,jdbcType=DECIMAL}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCoinIcon() != null) {
            SET("coin_icon = #{record.coinIcon,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cwv_user_wallet");
        
        SET("wallet_id = #{record.walletId,jdbcType=INTEGER}");
        SET("user_id = #{record.userId,jdbcType=INTEGER}");
        SET("coin_type = #{record.coinType,jdbcType=TINYINT}");
        SET("account = #{record.account,jdbcType=VARCHAR}");
        SET("balance = #{record.balance,jdbcType=DECIMAL}");
        SET("topup_balance = #{record.topupBalance,jdbcType=DECIMAL}");
        SET("draw_count = #{record.drawCount,jdbcType=INTEGER}");
        SET("draw_count_history = #{record.drawCountHistory,jdbcType=INTEGER}");
        SET("draw_count_record = #{record.drawCountRecord,jdbcType=INTEGER}");
        SET("income_ordinary = #{record.incomeOrdinary,jdbcType=DECIMAL}");
        SET("income_typical = #{record.incomeTypical,jdbcType=DECIMAL}");
        SET("income_functional = #{record.incomeFunctional,jdbcType=DECIMAL}");
        SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("coin_icon = #{record.coinIcon,jdbcType=VARCHAR}");
        
        CWVUserWalletExample example = (CWVUserWalletExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    public String updateByPrimaryKeySelective(CWVUserWallet record) {
        BEGIN();
        UPDATE("cwv_user_wallet");
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getCoinType() != null) {
            SET("coin_type = #{coinType,jdbcType=TINYINT}");
        }
        
        if (record.getAccount() != null) {
            SET("account = #{account,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            SET("balance = #{balance,jdbcType=DECIMAL}");
        }
        
        if (record.getTopupBalance() != null) {
            SET("topup_balance = #{topupBalance,jdbcType=DECIMAL}");
        }
        
        if (record.getDrawCount() != null) {
            SET("draw_count = #{drawCount,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountHistory() != null) {
            SET("draw_count_history = #{drawCountHistory,jdbcType=INTEGER}");
        }
        
        if (record.getDrawCountRecord() != null) {
            SET("draw_count_record = #{drawCountRecord,jdbcType=INTEGER}");
        }
        
        if (record.getIncomeOrdinary() != null) {
            SET("income_ordinary = #{incomeOrdinary,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeTypical() != null) {
            SET("income_typical = #{incomeTypical,jdbcType=DECIMAL}");
        }
        
        if (record.getIncomeFunctional() != null) {
            SET("income_functional = #{incomeFunctional,jdbcType=DECIMAL}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCoinIcon() != null) {
            SET("coin_icon = #{coinIcon,jdbcType=VARCHAR}");
        }
        
        WHERE("wallet_id = #{walletId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Wed May 23 22:06:41 CST 2018
     */
    protected void applyWhere(CWVUserWalletExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}