package org.brewchain.cwv.dbgens.market.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="cwv_market_auction")
@AllArgsConstructor
@NoArgsConstructor
public class CWVMarketAuction extends CWVMarketAuctionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_auction.bid_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    private Integer bidId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_auction.user_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_auction.bid_price
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    private BigDecimal bidPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_auction.status
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_auction.create_time
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_auction.bid_id
     *
     * @return the value of cwv_market_auction.bid_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public Integer getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_auction.bid_id
     *
     * @param bidId the value for cwv_market_auction.bid_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public void setBidId(Integer bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_auction.user_id
     *
     * @return the value of cwv_market_auction.user_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_auction.user_id
     *
     * @param userId the value for cwv_market_auction.user_id
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_auction.bid_price
     *
     * @return the value of cwv_market_auction.bid_price
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public BigDecimal getBidPrice() {
        return bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_auction.bid_price
     *
     * @param bidPrice the value for cwv_market_auction.bid_price
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public void setBidPrice(BigDecimal bidPrice) {
        this.bidPrice = bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_auction.status
     *
     * @return the value of cwv_market_auction.status
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_auction.status
     *
     * @param status the value for cwv_market_auction.status
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_auction.create_time
     *
     * @return the value of cwv_market_auction.create_time
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_auction.create_time
     *
     * @param createTime the value for cwv_market_auction.create_time
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CWVMarketAuction other = (CWVMarketAuction) that;
        return (this.getAuctionId() == null ? other.getAuctionId() == null : this.getAuctionId().equals(other.getAuctionId()))
            && (this.getBidId() == null ? other.getBidId() == null : this.getBidId().equals(other.getBidId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBidPrice() == null ? other.getBidPrice() == null : this.getBidPrice().equals(other.getBidPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAuctionId() == null) ? 0 : getAuctionId().hashCode());
        result = prime * result + ((getBidId() == null) ? 0 : getBidId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBidPrice() == null) ? 0 : getBidPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_auction
     *
     * @mbggenerated Thu May 03 14:40:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bidId=").append(bidId);
        sb.append(", userId=").append(userId);
        sb.append(", bidPrice=").append(bidPrice);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}