package org.brewchain.cwv.dbgens.market.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="cwv_market_exception")
@AllArgsConstructor
@NoArgsConstructor
public class CWVMarketException extends CWVMarketExceptionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_exception.type
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_exception.market_id
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    private Integer marketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_exception.description
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_exception.remark
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_market_exception.status
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_exception.type
     *
     * @return the value of cwv_market_exception.type
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_exception.type
     *
     * @param type the value for cwv_market_exception.type
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_exception.market_id
     *
     * @return the value of cwv_market_exception.market_id
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public Integer getMarketId() {
        return marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_exception.market_id
     *
     * @param marketId the value for cwv_market_exception.market_id
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public void setMarketId(Integer marketId) {
        this.marketId = marketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_exception.description
     *
     * @return the value of cwv_market_exception.description
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_exception.description
     *
     * @param description the value for cwv_market_exception.description
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_exception.remark
     *
     * @return the value of cwv_market_exception.remark
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_exception.remark
     *
     * @param remark the value for cwv_market_exception.remark
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_market_exception.status
     *
     * @return the value of cwv_market_exception.status
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_market_exception.status
     *
     * @param status the value for cwv_market_exception.status
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exception
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CWVMarketException other = (CWVMarketException) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getMarketId() == null ? other.getMarketId() == null : this.getMarketId().equals(other.getMarketId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exception
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getMarketId() == null) ? 0 : getMarketId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_exception
     *
     * @mbggenerated Fri Aug 03 16:45:16 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", type=").append(type);
        sb.append(", marketId=").append(marketId);
        sb.append(", description=").append(description);
        sb.append(", remark=").append(remark);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}