package org.brewchain.cwv.dbgens.market.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class CWVMarketBidCopyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public CWVMarketBidCopyExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBidIdIsNull() {
            addCriterion("bid_id is null");
            return (Criteria) this;
        }

        public Criteria andBidIdIsNotNull() {
            addCriterion("bid_id is not null");
            return (Criteria) this;
        }

        public Criteria andBidIdEqualTo(Integer value) {
            addCriterion("bid_id =", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdNotEqualTo(Integer value) {
            addCriterion("bid_id <>", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdGreaterThan(Integer value) {
            addCriterion("bid_id >", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bid_id >=", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdLessThan(Integer value) {
            addCriterion("bid_id <", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdLessThanOrEqualTo(Integer value) {
            addCriterion("bid_id <=", value, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdIn(List<Integer> values) {
            addCriterion("bid_id in", values, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdNotIn(List<Integer> values) {
            addCriterion("bid_id not in", values, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdBetween(Integer value1, Integer value2) {
            addCriterion("bid_id between", value1, value2, "bidId");
            return (Criteria) this;
        }

        public Criteria andBidIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bid_id not between", value1, value2, "bidId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdIsNull() {
            addCriterion("game_property_id is null");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdIsNotNull() {
            addCriterion("game_property_id is not null");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdEqualTo(Integer value) {
            addCriterion("game_property_id =", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdNotEqualTo(Integer value) {
            addCriterion("game_property_id <>", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdGreaterThan(Integer value) {
            addCriterion("game_property_id >", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_property_id >=", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdLessThan(Integer value) {
            addCriterion("game_property_id <", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdLessThanOrEqualTo(Integer value) {
            addCriterion("game_property_id <=", value, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdIn(List<Integer> values) {
            addCriterion("game_property_id in", values, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdNotIn(List<Integer> values) {
            addCriterion("game_property_id not in", values, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdBetween(Integer value1, Integer value2) {
            addCriterion("game_property_id between", value1, value2, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andGamePropertyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("game_property_id not between", value1, value2, "gamePropertyId");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Integer value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Integer value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Integer value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Integer value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Integer> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Integer> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Integer value1, Integer value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andAuctionStartIsNull() {
            addCriterion("auction_start is null");
            return (Criteria) this;
        }

        public Criteria andAuctionStartIsNotNull() {
            addCriterion("auction_start is not null");
            return (Criteria) this;
        }

        public Criteria andAuctionStartEqualTo(Date value) {
            addCriterion("auction_start =", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartNotEqualTo(Date value) {
            addCriterion("auction_start <>", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartGreaterThan(Date value) {
            addCriterion("auction_start >", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartGreaterThanOrEqualTo(Date value) {
            addCriterion("auction_start >=", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartLessThan(Date value) {
            addCriterion("auction_start <", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartLessThanOrEqualTo(Date value) {
            addCriterion("auction_start <=", value, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartIn(List<Date> values) {
            addCriterion("auction_start in", values, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartNotIn(List<Date> values) {
            addCriterion("auction_start not in", values, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartBetween(Date value1, Date value2) {
            addCriterion("auction_start between", value1, value2, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionStartNotBetween(Date value1, Date value2) {
            addCriterion("auction_start not between", value1, value2, "auctionStart");
            return (Criteria) this;
        }

        public Criteria andAuctionEndIsNull() {
            addCriterion("auction_end is null");
            return (Criteria) this;
        }

        public Criteria andAuctionEndIsNotNull() {
            addCriterion("auction_end is not null");
            return (Criteria) this;
        }

        public Criteria andAuctionEndEqualTo(Date value) {
            addCriterion("auction_end =", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndNotEqualTo(Date value) {
            addCriterion("auction_end <>", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndGreaterThan(Date value) {
            addCriterion("auction_end >", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndGreaterThanOrEqualTo(Date value) {
            addCriterion("auction_end >=", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndLessThan(Date value) {
            addCriterion("auction_end <", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndLessThanOrEqualTo(Date value) {
            addCriterion("auction_end <=", value, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndIn(List<Date> values) {
            addCriterion("auction_end in", values, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndNotIn(List<Date> values) {
            addCriterion("auction_end not in", values, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndBetween(Date value1, Date value2) {
            addCriterion("auction_end between", value1, value2, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andAuctionEndNotBetween(Date value1, Date value2) {
            addCriterion("auction_end not between", value1, value2, "auctionEnd");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderIsNull() {
            addCriterion("increase_ladder is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderIsNotNull() {
            addCriterion("increase_ladder is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderEqualTo(Long value) {
            addCriterion("increase_ladder =", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderNotEqualTo(Long value) {
            addCriterion("increase_ladder <>", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderGreaterThan(Long value) {
            addCriterion("increase_ladder >", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderGreaterThanOrEqualTo(Long value) {
            addCriterion("increase_ladder >=", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderLessThan(Long value) {
            addCriterion("increase_ladder <", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderLessThanOrEqualTo(Long value) {
            addCriterion("increase_ladder <=", value, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderIn(List<Long> values) {
            addCriterion("increase_ladder in", values, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderNotIn(List<Long> values) {
            addCriterion("increase_ladder not in", values, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderBetween(Long value1, Long value2) {
            addCriterion("increase_ladder between", value1, value2, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andIncreaseLadderNotBetween(Long value1, Long value2) {
            addCriterion("increase_ladder not between", value1, value2, "increaseLadder");
            return (Criteria) this;
        }

        public Criteria andBidStartIsNull() {
            addCriterion("bid_start is null");
            return (Criteria) this;
        }

        public Criteria andBidStartIsNotNull() {
            addCriterion("bid_start is not null");
            return (Criteria) this;
        }

        public Criteria andBidStartEqualTo(BigDecimal value) {
            addCriterion("bid_start =", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartNotEqualTo(BigDecimal value) {
            addCriterion("bid_start <>", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartGreaterThan(BigDecimal value) {
            addCriterion("bid_start >", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bid_start >=", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartLessThan(BigDecimal value) {
            addCriterion("bid_start <", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bid_start <=", value, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartIn(List<BigDecimal> values) {
            addCriterion("bid_start in", values, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartNotIn(List<BigDecimal> values) {
            addCriterion("bid_start not in", values, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bid_start between", value1, value2, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidStartNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bid_start not between", value1, value2, "bidStart");
            return (Criteria) this;
        }

        public Criteria andBidAmountIsNull() {
            addCriterion("bid_amount is null");
            return (Criteria) this;
        }

        public Criteria andBidAmountIsNotNull() {
            addCriterion("bid_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBidAmountEqualTo(BigDecimal value) {
            addCriterion("bid_amount =", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountNotEqualTo(BigDecimal value) {
            addCriterion("bid_amount <>", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountGreaterThan(BigDecimal value) {
            addCriterion("bid_amount >", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bid_amount >=", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountLessThan(BigDecimal value) {
            addCriterion("bid_amount <", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bid_amount <=", value, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountIn(List<BigDecimal> values) {
            addCriterion("bid_amount in", values, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountNotIn(List<BigDecimal> values) {
            addCriterion("bid_amount not in", values, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bid_amount between", value1, value2, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBidAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bid_amount not between", value1, value2, "bidAmount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountIsNull() {
            addCriterion("bidders_count is null");
            return (Criteria) this;
        }

        public Criteria andBiddersCountIsNotNull() {
            addCriterion("bidders_count is not null");
            return (Criteria) this;
        }

        public Criteria andBiddersCountEqualTo(Integer value) {
            addCriterion("bidders_count =", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountNotEqualTo(Integer value) {
            addCriterion("bidders_count <>", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountGreaterThan(Integer value) {
            addCriterion("bidders_count >", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("bidders_count >=", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountLessThan(Integer value) {
            addCriterion("bidders_count <", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountLessThanOrEqualTo(Integer value) {
            addCriterion("bidders_count <=", value, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountIn(List<Integer> values) {
            addCriterion("bidders_count in", values, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountNotIn(List<Integer> values) {
            addCriterion("bidders_count not in", values, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountBetween(Integer value1, Integer value2) {
            addCriterion("bidders_count between", value1, value2, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andBiddersCountNotBetween(Integer value1, Integer value2) {
            addCriterion("bidders_count not between", value1, value2, "biddersCount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeIsNull() {
            addCriterion("announce_time is null");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeIsNotNull() {
            addCriterion("announce_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeEqualTo(Date value) {
            addCriterion("announce_time =", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeNotEqualTo(Date value) {
            addCriterion("announce_time <>", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeGreaterThan(Date value) {
            addCriterion("announce_time >", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("announce_time >=", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeLessThan(Date value) {
            addCriterion("announce_time <", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeLessThanOrEqualTo(Date value) {
            addCriterion("announce_time <=", value, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeIn(List<Date> values) {
            addCriterion("announce_time in", values, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeNotIn(List<Date> values) {
            addCriterion("announce_time not in", values, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeBetween(Date value1, Date value2) {
            addCriterion("announce_time between", value1, value2, "announceTime");
            return (Criteria) this;
        }

        public Criteria andAnnounceTimeNotBetween(Date value1, Date value2) {
            addCriterion("announce_time not between", value1, value2, "announceTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(create_user) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 11 21:04:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cwv_market_bid_copy
     *
     * @mbggenerated Mon Jun 11 21:04:01 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}