package org.brewchain.cwv.dbgens.user.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="cwv_user_wallet")
@AllArgsConstructor
@NoArgsConstructor
public class CWVUserWallet extends CWVUserWalletKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_user_wallet.user_id
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_user_wallet.balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_user_wallet.topup_balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    private BigDecimal topupBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_user_wallet.draw_count
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    private Integer drawCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_user_wallet.last_update_time
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_user_wallet.user_id
     *
     * @return the value of cwv_user_wallet.user_id
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_user_wallet.user_id
     *
     * @param userId the value for cwv_user_wallet.user_id
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_user_wallet.balance
     *
     * @return the value of cwv_user_wallet.balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_user_wallet.balance
     *
     * @param balance the value for cwv_user_wallet.balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_user_wallet.topup_balance
     *
     * @return the value of cwv_user_wallet.topup_balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public BigDecimal getTopupBalance() {
        return topupBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_user_wallet.topup_balance
     *
     * @param topupBalance the value for cwv_user_wallet.topup_balance
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public void setTopupBalance(BigDecimal topupBalance) {
        this.topupBalance = topupBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_user_wallet.draw_count
     *
     * @return the value of cwv_user_wallet.draw_count
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public Integer getDrawCount() {
        return drawCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_user_wallet.draw_count
     *
     * @param drawCount the value for cwv_user_wallet.draw_count
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public void setDrawCount(Integer drawCount) {
        this.drawCount = drawCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_user_wallet.last_update_time
     *
     * @return the value of cwv_user_wallet.last_update_time
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_user_wallet.last_update_time
     *
     * @param lastUpdateTime the value for cwv_user_wallet.last_update_time
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CWVUserWallet other = (CWVUserWallet) that;
        return (this.getWalletId() == null ? other.getWalletId() == null : this.getWalletId().equals(other.getWalletId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getTopupBalance() == null ? other.getTopupBalance() == null : this.getTopupBalance().equals(other.getTopupBalance()))
            && (this.getDrawCount() == null ? other.getDrawCount() == null : this.getDrawCount().equals(other.getDrawCount()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWalletId() == null) ? 0 : getWalletId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getTopupBalance() == null) ? 0 : getTopupBalance().hashCode());
        result = prime * result + ((getDrawCount() == null) ? 0 : getDrawCount().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_user_wallet
     *
     * @mbggenerated Tue Apr 10 11:08:40 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", balance=").append(balance);
        sb.append(", topupBalance=").append(topupBalance);
        sb.append(", drawCount=").append(drawCount);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}