package org.brewchain.cwv.dbgens.game.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="cwv_game_dic")
@AllArgsConstructor
@NoArgsConstructor
public class CWVGameDic extends CWVGameDicKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_dic.key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_dic.value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_dic.parent_key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    private String parentKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_dic.parent_value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    private String parentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_dic.seq
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    private Short seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_dic.key
     *
     * @return the value of cwv_game_dic.key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_dic.key
     *
     * @param key the value for cwv_game_dic.key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_dic.value
     *
     * @return the value of cwv_game_dic.value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_dic.value
     *
     * @param value the value for cwv_game_dic.value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_dic.parent_key
     *
     * @return the value of cwv_game_dic.parent_key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public String getParentKey() {
        return parentKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_dic.parent_key
     *
     * @param parentKey the value for cwv_game_dic.parent_key
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public void setParentKey(String parentKey) {
        this.parentKey = parentKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_dic.parent_value
     *
     * @return the value of cwv_game_dic.parent_value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public String getParentValue() {
        return parentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_dic.parent_value
     *
     * @param parentValue the value for cwv_game_dic.parent_value
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public void setParentValue(String parentValue) {
        this.parentValue = parentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_dic.seq
     *
     * @return the value of cwv_game_dic.seq
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public Short getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_dic.seq
     *
     * @param seq the value for cwv_game_dic.seq
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    public void setSeq(Short seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CWVGameDic other = (CWVGameDic) that;
        return (this.getDicId() == null ? other.getDicId() == null : this.getDicId().equals(other.getDicId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getParentKey() == null ? other.getParentKey() == null : this.getParentKey().equals(other.getParentKey()))
            && (this.getParentValue() == null ? other.getParentValue() == null : this.getParentValue().equals(other.getParentValue()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDicId() == null) ? 0 : getDicId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getParentKey() == null) ? 0 : getParentKey().hashCode());
        result = prime * result + ((getParentValue() == null) ? 0 : getParentValue().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_dic
     *
     * @mbggenerated Thu Apr 26 16:31:47 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", parentKey=").append(parentKey);
        sb.append(", parentValue=").append(parentValue);
        sb.append(", seq=").append(seq);
        sb.append("]");
        return sb.toString();
    }
}