package org.brewchain.cwv.dbgens.game.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="cwv_game_tx_handle")
@AllArgsConstructor
@NoArgsConstructor
public class CWVGameTxHandle extends CWVGameTxHandleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_tx_handle.type
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_tx_handle.tx_hash
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    private String txHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_tx_handle.description
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwv_game_tx_handle.status
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_tx_handle.type
     *
     * @return the value of cwv_game_tx_handle.type
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_tx_handle.type
     *
     * @param type the value for cwv_game_tx_handle.type
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_tx_handle.tx_hash
     *
     * @return the value of cwv_game_tx_handle.tx_hash
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_tx_handle.tx_hash
     *
     * @param txHash the value for cwv_game_tx_handle.tx_hash
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_tx_handle.description
     *
     * @return the value of cwv_game_tx_handle.description
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_tx_handle.description
     *
     * @param description the value for cwv_game_tx_handle.description
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwv_game_tx_handle.status
     *
     * @return the value of cwv_game_tx_handle.status
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwv_game_tx_handle.status
     *
     * @param status the value for cwv_game_tx_handle.status
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CWVGameTxHandle other = (CWVGameTxHandle) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTxHash() == null ? other.getTxHash() == null : this.getTxHash().equals(other.getTxHash()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTxHash() == null) ? 0 : getTxHash().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwv_game_tx_handle
     *
     * @mbggenerated Fri Jul 20 14:49:37 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", type=").append(type);
        sb.append(", txHash=").append(txHash);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}